spring.application.name=book-manager
server.port=${PORT:8080}

# Config for database
spring.data.mongodb.uri=${DBURI}
spring.data.mongodb.database=${DATABASE}

# Config fo token secret
api.security.token.secret=${JWT_SECRET:default-secret}

# Configuração dos logs
logging.pattern.level=%5p [${spring.application.name:},%X{trace_id},%X{span_id}]